console.writeline ("Branca como a neve, o coração é uma pedra")
console.writeline ("Gelo que até cede, mas no fim ele não quebra")
console.writeline ("Tentei o quanto deu e nunca adiantou de nada")
console.writeline ("Gelo não derreteu, mas a chama foi apagada")
console.writeline ("Branca como a neve, o coração é uma pedra")
console.writeline ("Gelo que até cede, mas no fim ele não quebra")
console.writeline ("Tentei o quanto deu e nunca adiantou de nada")
console.writeline ("Gelo não derreteu, mas a chama foi apagada")
console.writeline ("Snow, nem vem tentar")
console.writeline ("Foi você quem decidiu que era melhor terminar")
console.writeline ("Então, nem vem atrás")
console.writeline ("Porque eu não sou brinquedo seu pra 'cê cansar e não querer mais")
console.writeline ("Snow, nem vem tentar")
console.writeline ("Foi você quem decidiu que era melhor terminar")
console.writeline ("Então, nem vem atrás")
console.writeline ("Porque eu não sou brinquedo seu pra 'cê cansar e não querer mais")
console.writeline ("'Cê fez seu castelinho na volta do coração")
console.writeline ("Achou que era melhor não confiar no sentimento")
console.writeline ("Agora que eu me fui, a sua torre foi pro chão")
console.writeline ("Tá toda quebrada, sofrendo, sentindo arrependimento")
console.writeline ("Snow white, perdeu o pai")
console.writeline ("Agora quer voltar atrás, reparou que quer mais")
console.writeline ("E não tem mais volta pra você e nem pra mim")
console.writeline ("'Cê que terminou primeiro, mas eu que 'tô pondo um fim")
console.writeline ("Snow, nem vem tentar")
console.writeline ("Foi você quem decidiu que era melhor terminar")
console.writeline ("Então, nem vem atrás")
console.writeline ("Porque eu não sou brinquedo seu pra 'cê cansar e não querer mais")
console.writeline ("Snow, nem vem tentar")
console.writeline ("Foi você quem decidiu que era melhor terminar")
console.writeline ("Então, nem vem atrás")
console.writeline ("Porque eu não sou brinquedo seu pra 'cê cansar e não querer mais")
console.writeline ("Snow, nem vem, não tem")
console.writeline ("Mas você frizou meu sentimento, me obrigou a te esquecer")
console.writeline ("E agora que sente falta, quer me ver")
console.writeline ("Falta quer me ver, yeah")